name: NCT-CBT DOCKER DEPLOYMENT

on:
  workflow_run:
    workflows: [NCT_QUESTION_BANK_CI]
    types:
      - completed

# vars and secrets to be specified in the settings panel of github repo

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [ubuntu-latest]

    # This is a matrix of all the possible OS and Node.js versions that will be tested
    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      #  Extract docker image metadata from the metadata actions
      - name: Extract Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # get details from github secrets and varibles
          images: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}

        # log in to docker  hub with your creds
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # set up docker builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # build and push image to docker hub
      - name: Build and Push Docker image to Doker Hub
        uses: docker/build-push-action@v6
        with:
          push: ${{github.event_name != 'pull_request'}} #nice block
          tags: ${{steps.meta.outputs.tags}}
          annotations: ${{steps.meta.outputs.annotations}}
          provenance: true
          sbom: true

  deploy-to-aws:
    if: ${{github.event_name != 'pull_request'}}
    needs: deploy
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker stop nct-cbt || true
            sudo docker rm -f nct-cbt || true
            sudo docker rmi -f  ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:main || true
            sudo docker pull ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:main
            sudo docker run -d --env-file=./nct-cbt/env --name nct-cbt -p 3000:80 ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:main
